---
name: POE-Component-IRC-Plugin-BrowserSupport
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  lookup browser support for
  CSS/HTML/JS from IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.001
  POE::Component::WWW::WebDevout::BrowserSupportInfo: 0.01
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::BrowserSupport:
    file: lib/POE/Component/IRC/Plugin/BrowserSupport.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
