---
abstract: 'lookup browser support for'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-BrowserSupport
provides:
  POE::Component::IRC::Plugin::BrowserSupport:
    file: lib/POE/Component/IRC/Plugin/BrowserSupport.pm
    version: 0.003
requires:
  Carp: 1.04
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.002
  POE::Component::WWW::WebDevout::BrowserSupportInfo: 0.01
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
